apiVersion: v1
kind: Service
metadata:
  name: {{ include "trento-web.fullname" . }}-collector
  labels:
    {{- include "trento-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.collectorService.type }}
  ports:
    - port: {{ .Values.collectorService.port }}
      targetPort: collector
      protocol: TCP
      name: collector
  selector:
    {{- include "trento-web.selectorLabels" . | nindent 4 }}
