apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "trento-web.fullname" . }}-prune-checks-results-cronjob
spec:
  schedule: {{ .Values.pruneChecksCronjobSchedule }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            args:
            - ctl
            - prune-checks-results
            - --olther-than
            - "30"
            - --db-host
            - {{ .Release.Name }}-postgresql
          restartPolicy: OnFailure
