apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trento-web.fullname" . }}-secret
type: Opaque
data:
  SECRET_KEY_BASE: {{ include "trento.web.secretKeyBase" . | quote }}
  SMTP_PASSWORD: {{ .Values.alerting.smtpPassword | b64enc | quote }}