name: Continuous Integration
concurrency: ci-${{ github.ref }}
on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "main"
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test-helm-charts:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v2.0
        with:
          version: v3.4.0
      - uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1
      - name: Lint
        run: ct lint --config=ct.yaml --lint-conf=helmlintconf.yaml
